services: 
  www:
    build: docker/php
    container_name: ecoride_symfony_php
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
    networks:
      - ecoride_symfony

  mysql:
    image: mysql
    container_name: ecoride_symfony_mysql
    volumes:
      - ./var/db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ecoride_symfony
    networks:
      - ecoride_symfony

  phpmyadmin:
    image: phpmyadmin
    container_name: ecoride_symfony_phpmyadmin
    ports:
      - 8780:80
    environment:
      PMA_HOST: mysql
    networks:
      - ecoride_symfony  


  mongodb:
    image: mongo:6.0
    container_name: ecoride_symfony_mongodb
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DB:-app}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-}
    volumes:
      - mongodb_data:/data/db
      
    networks:
      - ecoride_symfony
      
networks:
  ecoride_symfony:

volumes:
  mongodb_data: